name: Setup auth
inputs:
  environment:
    description: 'what environment to deploy for (dev / prod)'
    required: true
  tailscale_id:
    description: 'Tailscale OAuth Client ID'
    required: true
  tailscale_secret:
    description: 'Tailscale OAuth Secret'
    required: true


runs:
  using: composite
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Connect to Tailnet
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ inputs.tailscale_id }}
        oauth-secret: ${{ inputs.tailscale_secret }}
        tags: tag:githubactions
        version: 1.68.1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        role-session-name: fund-manager-dev
        role-to-assume: arn:aws:iam::494494944992:role/GithubImagePusher
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [dns]
            nameservers=["100.100.100.100"]
