version: '3.8'

# Note: PostgreSQL has been replaced with SQLite
# The database is now a single file that doesn't require a separate service
# To use the application with SQLite:
# 1. Set DATABASE_PATH environment variable to the desired database file location
# 2. The application will automatically create the SQLite database file if it doesn't exist
# 3. Example: DATABASE_PATH=./data/ironbird.db

# If you need to add other services in the future, you can add them here
services:
  # Placeholder for future services
  # Example:
  # app:
  #   build: .
  #   environment:
  #     - DATABASE_PATH=./data/ironbird.db
  #   volumes:
  #     - ./data:/app/data
  #   ports:
  #     - "8080:8080"

# No volumes needed for SQLite as it's a file-based database
# volumes:
