chains:
  cosmos:
    name: cosmos
    version: v21.0.1
    dependencies:
      skip-mev/ironbird-cometbft: cometbft/cometbft
    image:
      dockerfile: "./hack/gaia.Dockerfile"
      gid: "1025"
      uid: "1025"
      binary_name: "gaiad"
      home_dir: "/gaiad"
      gas_prices: "0.00025uatom"
    num_of_validators: 6
    num_of_nodes: 0

  simapp:
    name: simapp
    version: v0.53.0-rc2
    dependencies:
      skip-mev/ironbird-cometbft: cometbft/cometbft
    image:
      dockerfile: "./hack/simapp.Dockerfile"
      gid: "1000"
      uid: "1000"
      binary_name: "/usr/bin/simd"
      home_dir: "/simd"
      gas_prices: "0.0005stake"
    num_of_validators: 6
    num_of_nodes: 0
    genesis_modifications:
      - key: consensus.params.block.max_gas
        value: "75000000"

load_tests:
  normal:
    name: normal
    description: "Runs a half-half mix of MsgSend and MsgMultiSend transactions at half block gas limit for 100 blocks"
    block_gas_limit_target: 0.5
    num_of_blocks: 100
    msgs:
      - weight: 0.5
        type: MsgSend
      - weight: 0.5
        type: MsgMultiSend

  full:
    name: full
    description: "Send MsgMultiSend transactions attempting to fill the block gas limit for 100 blocks"
    block_gas_limit_target: 1
    num_of_blocks: 100
    msgs:
      - weight: 1
        type: MsgMultiSend
