chains:
  cosmos:
    name: cosmos
    version: v21.0.1
    dependencies:
      skip-mev/ironbird-cometbft: github.com/cometbft/cometbft
      skip-mev/ironbird-cosmos-sdk: github.com/cosmos/cosmos-sdk
      cometbft/cometbft: github.com/cometbft/cometbft
      cosmos/cosmos-sdk: github.com/cosmos/cosmos-sdk
    image:
      dockerfile: "./hack/gaia.Dockerfile"
      gid: "1025"
      uid: "1025"
      binary_name: "gaiad"
      home_dir: "/gaiad"
      gas_prices: "0.00025uatom"
    num_of_validators: 6
    num_of_nodes: 0

  simapp-v47:
    name: simapp-v47
    version: v0.47.17
    dependencies:
      skip-mev/ironbird-cometbft: github.com/cometbft/cometbft
      cometbft/cometbft: github.com/cometbft/cometbft
      skip-mev/ironbird-cosmos-sdk: github.com/cosmos/cosmos-sdk
      cosmos/cosmos-sdk: github.com/cosmos/cosmos-sdk
    image:
      dockerfile: "./hack/simapp.Dockerfile"
      gid: "1000"
      uid: "1000"
      binary_name: "/usr/bin/simd"
      home_dir: "/simd"
      gas_prices: "0.0005stake"
    num_of_validators: 6
    num_of_nodes: 0
    genesis_modifications:
      - key: consensus_params.block.max_gas
        value: "75000000"

  simapp-v50:
    name: simapp-v50
    version: v0.50.13
    dependencies:
      skip-mev/ironbird-cometbft: cometbft/cometbft
      skip-mev/ironbird-cosmos-sdk: cosmos/cosmos-sdk
      cometbft/cometbft: cometbft/cometbft
      cosmos/cosmos-sdk: cosmos/cosmos-sdk
    image:
      dockerfile: "./hack/simapp.Dockerfile"
      gid: "1000"
      uid: "1000"
      binary_name: "/usr/bin/simd"
      home_dir: "/simd"
      gas_prices: "0.0005stake"
    num_of_validators: 6
    num_of_nodes: 0
    genesis_modifications:
      - key: consensus.params.block.max_gas
        value: "75000000"

  simapp-v53:
    name: simapp-v53
    version: v0.53.0
    dependencies:
      skip-mev/ironbird-cometbft: github.com/cometbft/cometbft
      skip-mev/ironbird-cosmos-sdk: github.com/cosmos/cosmos-sdk
      cometbft/cometbft: github.com/cometbft/cometbft
      cosmos/cosmos-sdk: github.com/cosmos/cosmos-sdk
    image:
      dockerfile: "./hack/simapp.Dockerfile"
      gid: "1000"
      uid: "1000"
      binary_name: "/usr/bin/simd"
      home_dir: "/simd"
      gas_prices: "0.0005stake"
    num_of_validators: 6
    num_of_nodes: 0
    genesis_modifications:
      - key: consensus.params.block.max_gas
        value: "75000000"

grafana:
  url: "https://skipprotocol.grafana.net"
  dashboards:
    - id: b8ff6e6f-5b4b-4d5e-bc50-91bbbf10f436
      name: "comet-performance"
      human_name: "CometBFT Performance"

load_tests:
  normal:
    name: normal
    description: "Runs a half-half mix of MsgSend and MsgMultiSend transactions at half block gas limit for 100 blocks"
    block_gas_limit_target: 0.5
    num_of_blocks: 100
    msgs:
      - weight: 0.5
        type: MsgSend
      - weight: 0.5
        type: MsgMultiSend

  full:
    name: full
    description: "Send MsgMultiSend transactions attempting to fill the block gas limit for 100 blocks"
    block_gas_limit_target: 1
    num_of_blocks: 100
    msgs:
      - weight: 1
        type: MsgMultiSend