// Code generated by MockGen. DO NOT EDIT.
// Source: activities/loadtest/loadtest.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/skip-mev/ironbird/petri/core/types"
)

// MocktheChain is a mock of theChain interface.
type MocktheChain struct {
	ctrl     *gomock.Controller
	recorder *MocktheChainMockRecorder
}

// MocktheChainMockRecorder is the mock recorder for MocktheChain.
type MocktheChainMockRecorder struct {
	mock *MocktheChain
}

// NewMocktheChain creates a new mock instance.
func NewMocktheChain(ctrl *gomock.Controller) *MocktheChain {
	mock := &MocktheChain{ctrl: ctrl}
	mock.recorder = &MocktheChainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktheChain) EXPECT() *MocktheChainMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MocktheChain) GetConfig() types.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(types.ChainConfig)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MocktheChainMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MocktheChain)(nil).GetConfig))
}

// GetValidators mocks base method.
func (m *MocktheChain) GetValidators() []types.NodeI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidators")
	ret0, _ := ret[0].([]types.NodeI)
	return ret0
}

// GetValidators indicates an expected call of GetValidators.
func (mr *MocktheChainMockRecorder) GetValidators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidators", reflect.TypeOf((*MocktheChain)(nil).GetValidators))
}

// GetNodes mocks base method.
func (m *MocktheChain) GetNodes() []types.NodeI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodes")
	ret0, _ := ret[0].([]types.NodeI)
	return ret0
}

// GetNodes indicates an expected call of GetNodes.
func (mr *MocktheChainMockRecorder) GetNodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodes", reflect.TypeOf((*MocktheChain)(nil).GetNodes))
}
